### ISSUE TITLE
"Data inconsistency detected" error when loading image in "Sighting" Screen when blob was not materialized yet

### ISSUE THREAD

**Issue by adzialocha** [p2panda/meli#153]
```
W/aquadoggo::http::api(18299): Data inconsistency detected: Blob document 0d44b9 exists in database but not on file
W/aquadoggo::http::api(18299):                 system at path /data/user/0/org.p2panda.meli.debug/files/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9!

======== Exception caught by image resource service ================================================
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:115:9)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1005:3)
<asynchronous suspension>
Image provider: NetworkImage("http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9", scale: 1.0)
Image key: NetworkImage("http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9", scale: 1.0)
====================================================================================================
I/aquadoggo::materializ..(18299): Creating blob at path /data/user/0/org.p2panda.meli.debug/files/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9
I/aquadoggo::materializ..(18299): Created <Document 4ba2a7>
======== Exception caught by image resource service ================================================
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:115:9)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1005:3)
<asynchronous suspension>
Image provider: NetworkImage("http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9", scale: 1.0)
Image key: NetworkImage("http://localhost:2020/blobs/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9", scale: 1.0)
====================================================================================================
I/aquadoggo::materializ..(18299): Creating blob at path /data/user/0/org.p2panda.meli.debug/files/00201aea9847b20be1054b1ef6088c85143e77cefae75ebaeab820ddf4c36a0d44b9
I/aquadoggo::materializ..(18299): Created <Document 4ba2a7>
```

**Comment by adzialocha** [comment]
![Screenshot_20240626_170348](https://github.com/p2panda/meli/assets/1822473/995ced44-7d6d-43e4-9613-4db7416f290c)

**Comment by adzialocha** [comment]
We're showing a cute bee in this moment, after reloading it should be gone
