### ISSUE TITLE
Unhandled Exception when saving description widget with empty string

### ISSUE THREAD

**Issue by adzialocha** [p2panda/meli#87]
Steps to reproduce:

1. Go to "Species Profile" screen
2. Click "Edit" in Description Widget, don't enter anything in field
3. Click "Edit" ("Save") button again

Error message:

```
E/flutter (12865): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (12865): #0      _TextFieldState._submit (package:app/ui/widgets/text_field.dart:51:34)
E/flutter (12865): #1      _TextFieldState._toggleEditMode.<anonymous closure> (package:app/ui/widgets/text_field.dart:65:9)
E/flutter (12865): #2      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
E/flutter (12865): #3      _TextFieldState._toggleEditMode (package:app/ui/widgets/text_field.dart:62:5)
E/flutter (12865): #4      EditableCard._content.<anonymous closure> (package:app/ui/widgets/editable_card.dart:35:25)
E/flutter (12865): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
E/flutter (12865): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
E/flutter (12865): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
E/flutter (12865): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
E/flutter (12865): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
E/flutter (12865): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
E/flutter (12865): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
E/flutter (12865): #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
E/flutter (12865): #13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
E/flutter (12865): #14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
E/flutter (12865): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
E/flutter (12865): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
E/flutter (12865): #17     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter (12865): #18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
E/flutter (12865): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
E/flutter (12865): 
```

**Comment by adzialocha** [comment]
Fixed via https://github.com/p2panda/meli/commit/1bdce46c8b3056a5fdb4aced594aa3a23af75efb
